### ISSUE TITLE
Invalid XML response from debugger with apache and perl

### ISSUE THREAD

**Issue by DavidEGx** [joonty/vdebug#148]
Hi,

Just trying to run the debugger using mod_perl I get the following error:

```
Waiting for a connection (Ctrl-C to cancel, this message will self-destruct in  20  seconds...)
An error occured: <class 'vdebug.dbgp.ResponseError'>Traceback (most recent call last):
  File "/home/david/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 31, in run self.runner.run()                                                                                                              
  File "/home/david/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 160, in run self.open()
  File "/home/david/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 45, in open vdebug.opts.Options.get('timeout',int))
  File "/home/david/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 276, in listen self.api = vdebug.dbgp.Api(connection)
  File "/home/david/.vim/bundle/vdebug/plugin/python/vdebug/dbgp.py", line 196, in __init__ self.__parse_init_msg(self.conn.recv_msg())
  File "/home/david/.vim/bundle/vdebug/plugin/python/vdebug/dbgp.py", line 205, in __parse_init_msg msg)                                                                               
ResponseError: ('Invalid XML response from debugger', '<?xml version="1.0" encoding="UTF-8" ?>
<response xmlns="urn:debugger_protocol_v1" command="run" status="stopping"    reason="ok" transaction_id="0"/>')
```

What I'm doing is:
1. Open Vim.
2. Press F5.
3. Restart apache.

My apache config is like the following:

```
<Perl>
use lib "/home/david/opt/lib/debug/";
</Perl>
PerlSetEnv PERLDB_OPTS "RemotePort=127.0.0.1:9000"
PerlRequire /home/david/opt/lib/debug/perl5db.pl
PerlSetEnv DBGP_IDEKEY "whatever"
```

I've tried different variations of that configuration and I get the same error.
I've tried the komodo 4.4.1 remote debugging module (as pointed in the documentation) and the last one (8.0.2), same error with both.

Is this a bug? Is something wrong in my configuration?

**Comment by joonty** [comment]
Hi @DavidEGx, sorry for not getting back to you on this. I'm not able to reproduce the issue, but I've been trying from the command line. Could you try running a simple command line script with the debugger and see whether you get the same issue? If you don't have the issue then that would suggest the problem is in the configuration you're supplying with mod_perl.

Thanks
