### ISSUE TITLE
Error when starting vim via git

### ISSUE THREAD

**Issue by tremby** [joonty/vdebug#176]
When starting vim via git, for instance during `git commit`, I get the error

```
Error detected while processing /Users/me/.vim/bundle/vdebug/plugin/vdebug.vim:
line   40:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/me/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 8, in <module>
    import socket
  File "/usr/local/Cellar/python/2.7.7_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 47, in <module>
    import _socket
ImportError: dlopen(/usr/local/Cellar/python/2.7.7_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_socket.so, 2): Symbol not found: __PyInt_AsInt
  Referenced from: /usr/local/Cellar/python/2.7.7_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_socket.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.7_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_socket.so
line  111:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'DebuggerInterface' is not defined
Press ENTER or type command to continue
```

I don't get this error when starting vim normally, and in fact the debugger works just fine.

This appears to be similar to #93. I have vim 7.4.

I get the same error when running `:pyfile /home/charetjc/.vim/bundle/vdebug/plugin/python/start_vdebug.py` after starting via git (not error after starting vim normally).

Is there any extra information I can give which would help point to a solution?

**Comment by joonty** [comment]
Closed - assumed fixed.

**Comment by tremby** [comment]
Well, not fixed as such. I
