### ISSUE TITLE
None of the commands work even after remapping

### ISSUE THREAD

**Issue by bgarrison25** [joonty/vdebug#184]
I have installed xdebug with vundle (CentOS / VIM 7.4 +python/dyn +signs). When I type F5 in a php file  it goes into Insert mode and puts in the letter T. Following directions from Issue 101 I added this to my vimrc file:

noremap <C-d> :python debugger.run()<CR>
noremap <C-e> :python debugger.step_over()<CR>
noremap <C-f> :python debugger.step_into()<CR>
noremap <C-r> :python debugger.step_out()<CR>

Now <C-d> successfuly starts the debugger / I reload the page and it starts up xdebug...SUCCESS! Nope. I then try any of the other commands and get the following:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: Debugger instance has no attribute 'step_over'

Obviously "step_over" is replaced with whatever command im trying to give it. 

So in recap:

1) installed vdebug
2) f5 wasn't working
3) followed instructions https://github.com/joonty/vdebug/issues/101
4) debugger starts but none of the step commands work.

**Comment by cadupont** [comment]
I have the same problem, but on Debian. My OSX setup works fine however.

**Comment by joonty** [comment]
Could anyone send me the full output of `vim --version`? That will help me in debugging.

Thanks

**Comment by DavidHernandez** [comment]
Having the same issue in Debian, here is the vim --version output:
```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:36:03)
Included patches: 1-488, 576
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by jamessan@debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux -lacl -lattr -lgpm -ldl
```

**Comment by DavidHernandez** [comment]
My problem was caused because python support wasn't enabled. After installing vim-nox, it got fixed.

**Comment by joonty** [comment]
:+1:

**Comment by runonce86** [comment]
I'm having a similar problem. None of the commands are working.

I have vim 7.4.1689 and vdebug 1.5.1 on Ubuntu 16.04. Also installed vim-gtk and vim-nox.

Command `python3 debugger.run()` returns:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'debugger' is not defined
```

Command `scrptnames` shows the path to the plugin:

`~/.vim/bundle/vdebug/plugin/vdebug.vim`

First tried manual install and then using pathogen.

Any clues?

**Comment by exussum12** [comment]
You need to install vim-py2-nox and use that. There us a gtk py2 build to. Either will be fine.

**Comment by runonce86** [comment]
@exussum12 Tried that but same result. Any other tip?

Here is the list of features:

```
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax   
```

**Comment by exussum12** [comment]
Yes your not running the py2 version.  Run vim-nox-py2 to start it. If that would you will need to run update alternatives to select the py2 version

**Comment by exussum12** [comment]
If its Debian based you should be able to type vim double tap enter and all of the vim xommand should show. Can't remember the order of nox and py2

**Comment by runonce86** [comment]
Thanks @exussum12!

Vdebug is working when using `vim.nox-py2` instead of `vim`.

**Comment by Morabaraba** [comment]
On Ubuntu 16.04 LTS Xenial:

```sh
sudo apt install vim-nox-py2
vim.nox-py2
```
and then `<F5>` and other `:Vdebug*` commands should work.

**Comment by jkufner** [comment]
Unfortunately, as time goes on, Python 2 is disappearing and vim.nox-py2 is not available anymore. It's been almost 10 years since Python 3.0 release.

**Comment by BlackIkeEagle** [comment]
closing because it might no longer be relevant, lots of things have changed over time
