### ISSUE TITLE
A slash at the third position implies that I work on Win*

### ISSUE THREAD

**Issue by paprykarz** [joonty/vdebug#205]
Hi Jon

This bug has place with paths of form "/a/b/..." with slash on the third position. 

	"DebuggerLog" [New File]
	An error occured: <class 'vim.error'>
	Traceback (most recent call last):
	  File "/home/paprykarz/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 31, in run
	    self.runner.run()
	  File "/home/paprykarz/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 160, in run
	    self.open()
	  File "/home/paprykarz/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 71, in open
	    self.refresh(status)
	  File "/home/paprykarz/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 122, in refresh
	    self.cur_lineno)
	  File "/home/paprykarz/.vim/bundle/vdebug/plugin/python/vdebug/ui/vimui.py", line 82, in set_source_position
	    self.sourcewin.place_pointer(lineno)
	  File "/home/paprykarz/.vim/bundle/vdebug/plugin/python/vdebug/ui/vimui.py", line 255, in place_pointer
	    ' file='+self.file)
	error: Vim(sign):E158: Invalid buffer name: ab^Dprojectnamepublicindex.php

Cause of this behavior is in the second and the third line from `_create_local` in `FilePath` (utils.py), added in 2be4513f6b1dfae0a728f8f5d3b3b43fbc33760b. After commenting these lines, vdebug starts correctly.

**Comment by joonty** [comment]
Ha! Fair enough. It looks like i'll also have to check for a colon at the second index - hopefully that will be safe enough.

Thanks for taking the time to report this.

**Comment by joonty** [comment]
Looks like this was fixed in https://github.com/joonty/vdebug/commit/fdcb1a9313a0974ffd1c50c5f0bc6dde1e7a76c5, which is on the dev branch. So it will go into 1.5.0 soon.

Thanks
