### ISSUE TITLE
Incompatible with new versions of ruby?

### ISSUE THREAD

**Issue by luiz-rocha** [joonty/vdebug#257]
$ ruby -I$RUBYDB_LIB -r $RUBYDB_LIB/rdbgp.rb  test.rb
Error: cannot load such file -- ruby-debug-base
	/home/user/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/home/user/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/home/user/Scripts/rubylib/rdbgp/loader.rb:21:in `<top (required)>'
	/home/user/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/home/user/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/home/user/Scripts/rubylib/rdbgp.rb:99:in `get_going'
	/home/user/Scripts/rubylib/rdbgp.rb:113:in `<top (required)>'
	/home/user/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/home/user/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
The Komodo ruby debugger couldn't load the ruby-debug-base component.
  This library ships with Komodo, but also can be installed by running `gem install ruby-debug-base'

$ gem install ruby-debug-base
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-debug-base:
	ERROR: Failed to build gem native extension.

    current directory: /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/linecache-1.3.1/ext/linecache
/home/user/.rbenv/versions/2.2.3/bin/ruby -r ./siteconf20161011-7632-o4zszt.rb extconf.rb
**Can't handle 1.9.x yet**
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/user/.rbenv/versions/2.2.3/bin/$(RUBY_BASE_NAME)

extconf failed, exit code 1

Gem files will remain installed in /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/linecache-1.3.1 for inspection.
Results logged to /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/linecache-1.3.1/gem_make.out

**Comment by fmarkwong** [comment]
same issue with Ruby 2.4

**Comment by BlackIkeEagle** [comment]
@joonty ideas? I'm not using ruby

**Comment by Shadowsith** [comment]
How about to change the ruby debugging to this gem: pry-byebug ?
Its a GDB-like console debugging tool and works well with ruby 2.6.x 
https://github.com/deivid-rodriguez/pry-byebug

It supports commands like break, next, continue etc. but don't know if this could be integrated in vdebug.

**Comment by duvifn** [comment]
FYI, The `Komodo IDE` (mentioned in the `VDebug` help) is shipped with a `rdbgp2.rb` file which is supposed be compatible with Ruby `2.x`.

This file contains a bug which prevents using it with `VDebug` (it streams the `stderr` to the IDE by default) and it also doesn't implement an `eval` command.

I managed to make it work (and added an `eval` command), but I'm pretty new to this so this is probably far from perfect.

If anyone wants to take it from here, I put the fixed file [here](https://github.com/duvifn/ruby_dbgp). It's version controlled, so you can easily see changes made to the original file.
