### ISSUE TITLE
decoding issue while debugging

### ISSUE THREAD

**Issue by BlackIkeEagle** [joonty/vdebug#290]
```
- [ERROR] {Wed 07 2017 10:34:25} An error occured: <type 'exceptions.UnicodeDecodeError'>
Traceback (most recent call last):
  File "/home/ike/.vim/plugged/vdebug/pythonx/vdebug/event.py", line 477, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/home/ike/.vim/plugged/vdebug/pythonx/vdebug/event.py", line 406, in run
    self.ui.windows.watch().accept_renderer(rend)
  File "/home/ike/.vim/plugged/vdebug/pythonx/vdebug/ui/vimui.py", line 533, in accept_renderer
    self.write(renderer.render())
  File "/home/ike/.vim/plugged/vdebug/pythonx/vdebug/ui/vimui.py", line 745, in render
    res += self.__render_property(prop,next_prop,final,indent)
  File "/home/ike/.vim/plugged/vdebug/pythonx/vdebug/ui/vimui.py", line 770, in __render_property
    "\\n'\n%(indent)s'"%{'indent':indent_str})}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)
```

**Comment by micalexander** [comment]
I am getting this same issue, same line numbers, same errors.

**Comment by lucc** [comment]
What do you do to get this. It is always helpful if you give some steps to reproduce this in a bugreport. If I look at that line I can not see the error so it has to depend on some value that comes from your specific situation.

**Comment by BlackIkeEagle** [comment]
sorry @lucc I had some other work to do so I dropped the ball a little here, I only pasted here to remember I had to look into it

**Comment by micalexander** [comment]
I was simply stepping through the code and started to receive this error.

**Comment by BlackIkeEagle** [comment]
this is currently fixed by making sure the data sent back to vim is formatted as ascii

**Comment by micalexander** [comment]
Receiving this error after the update:

```
Traceback (most recent call last):
  File "/home/micalexander/.config/nvim/.cache/init.vim/.dein/pythonx/vdebug/event.py", line 524, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/home/micalexander/.config/nvim/.cache/init.vim/.dein/pythonx/vdebug/event.py", line 439, in run
    self.ui.windows.watch().accept_renderer(rend)
  File "/home/micalexander/.config/nvim/.cache/init.vim/.dein/pythonx/vdebug/ui/vimui.py", line 537, in accept_renderer
    self.write(renderer.render())
  File "/home/micalexander/.config/nvim/.cache/init.vim/.dein/pythonx/vdebug/ui/vimui.py", line 770, in render
    res += self.__render_property(prop, next_prop, final, indent)
  File "/home/micalexander/.config/nvim/.cache/init.vim/.dein/pythonx/vdebug/ui/vimui.py", line 794, in __render_property
    'value': " " + p.value.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f609' in position 1: ordinal not in range(128)
```

**Comment by BlackIkeEagle** [comment]
:( this is so annoying. it was working before, then for me the ascii trick seems to work, but for you @micalexander its seems not to fix anything

**Comment by micalexander** [comment]
@BlackIkeEagle I am willing to do any debugging necessary to get this to work as this is the only xdebug plugin I can seem to find for vim. Is there anything else I can provide that can help you get to the source of the issue?

**Comment by BlackIkeEagle** [comment]
As an update I think the encoding issues should be all fixed now in v2-integration
