### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by jaimealsilva** [joonty/vdebug#296]
I'm running Ubuntu Zesty (17.04) and it has dropped support for Python 2 (no more vim-...-py2 packages) so vdebug (and a long list of plugins) has stopped working. It seems development of this module has stopped (I think I read somewhere joonty has switched to Ruby and is no longer interested in PHP).

I'm a vimaholic which makes its income from PHP development (manly, among other languages) so:

- Is there an alternative to this plugin that works on vim with Python 3 ?
- If not, how hard it is to make this one work on Python 3?
- Will v2 of this plugin be done? will it work with Python 3?

Thanks.

```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 17 2017 12:13:35)
Included patches: 1-95
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-8krYYf/vim-8.0.0095=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.24/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm     
```

**Comment by lucc** [comment]
There is a branch `v2-integration` where some people continue to develop. We are working towards py3 but are not there yet.

I think it can only help if you also join in :)

**Comment by l0rb** [comment]
This has a bounty now https://www.bountysource.com/issues/46922753-support-for-python-3

**Comment by markkimsal** [comment]
I have hacked python3 support into a branch based off of v2-integration branch.  It mostly involves changing :python to :python3 and :pyfile to :py3file plus changing all the networking and sockets to use byte-like objects instead of strings.  I cannot get the test code to pass because faking byte-like objects for the mock sockets seems to be beyond my skill.

I'm not sure what the intent of this project is with regrades to dropping python 2 support.  But, I'm able to use vdebug on Ubuntu 17.10 with vim + python3.

https://github.com/markkimsal/vdebug/tree/python3

**Comment by BlackIkeEagle** [comment]
@markkimsal Could you open a Pull Request, so we could continue from there

**Comment by Mte90** [comment]
I tried locally and seems that version works :-D

**Comment by canaaerus** [comment]
Thanks for your work, markkimsal, it works surprisingly well.
One thing I have problems with  is that `:VdebugEval` often yields these errors:
```
Traceback (most recent call last):
  File "/home/bodo/.vim/pack/minpac/start/vdebug/pythonx/vdebug/event.py", line 524, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/home/bodo/.vim/pack/minpac/start/vdebug/pythonx/vdebug/event.py", line 368, in run
    self.ui.windows.watch().accept_renderer(rend)
  File "/home/bodo/.vim/pack/minpac/start/vdebug/pythonx/vdebug/ui/vimui.py", line 537, in accept_renderer
    self.write(renderer.render())
  File "/home/bodo/.vim/pack/minpac/start/vdebug/pythonx/vdebug/ui/vimui.py", line 759, in render
    properties = self.response.get_context()
  File "/home/bodo/.vim/pack/minpac/start/vdebug/pythonx/vdebug/dbgp.py", line 158, in get_context
    self.create_properties(EvalProperty(c, code, self.api.language))
TypeError: can't concat bytes to str
```

**Comment by BlackIkeEagle** [comment]
@bodograumann That issue is fixed in v2-integration now :), there are some small issues left
