### ISSUE TITLE
vdebug can't open ui on connection

### ISSUE THREAD

**Issue by seagoj** [joonty/vdebug#301]
my setup:
- vdebug: 96b51f3
- neovim: 0.2.0
- python2: 2.7.13
- pip-neovim: 0.1.13

vdebug can't open the ui upon connection. I have to hit escape, which triggers the following error, after which the UI opens and I can connect as normal.

```
- [Debug] {Wed 06 2017 23:03:15} Closing the socket
- [ERROR] {Wed 06 2017 23:03:15} An error occured: <class 'neovim.api.nvim.NvimError'>
Traceback (most recent call last):
  File "/Users/seagoj/dotfiles/nvim/.config/nvim/plugged/vdebug/plugin/python/start_vdebug.py", line 31, in run
    self.runner.run()
  File "/Users/seagoj/dotfiles/nvim/.config/nvim/plugged/vdebug/plugin/python/vdebug/runner.py", line 184, in run
    self.open()
  File "/Users/seagoj/dotfiles/nvim/.config/nvim/plugged/vdebug/plugin/python/vdebug/runner.py", line 48, in open
    self.ui.open()
  File "/Users/seagoj/dotfiles/nvim/.config/nvim/plugged/vdebug/plugin/python/vdebug/ui/vimui.py", line 79, in open
    raise e
NvimError: Vim(wincmd):E16: Invalid range
```

Thanks in advance for any help you can give me.

**Comment by reafle** [comment]
related to #305  ?

**Comment by seagoj** [comment]
I think my issue may have been related to python after all. It works now.
