### ISSUE TITLE
Vdebug crash with small screen resolutions

### ISSUE THREAD

**Issue by gdance** [joonty/vdebug#50]
Hello I am trying to debug a PHP script and I set a breakpoint and hit <F5> to start debugging and it did what is illustrated in the screenshot and then gave this error message.
![vdebug error](https://f.cloud.github.com/assets/631496/191537/73a8323a-7f3c-11e2-90ca-9792b8154c72.jpg)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gdance/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 31, in run
    self.runner.run()
  File "/Users/gdance/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 137, in run
    self.open()
  File "/Users/gdance/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 42, in open
    self.ui.open()
  File "/Users/gdance/.vim/bundle/vdebug/plugin/python/vdebug/ui/vimui.py", line 28, in open
    vim.command('silent tabnew ' + cur_buf_name)

**Comment by BlackIkeEagle** [comment]
it will be massively hard to debug on small screen resultions so closing this
